apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-app
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/echo
    repoURL: git@github.com:c6h3un/argocd-demo-example.git
    targetRevision: multi-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: false