apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-app
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: git@github.com:c6h3un/argocd-demo-example.git
  syncPolicy:
    automated:
      prune: true # git 上面的刪除，會不會需要去刪除對應 OCP 上面的 resource 
      selfHeal: true # OCP 上面上面有手動修改，ArgoCD 會去改回來 