# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#ssh-repositories 
apiVersion: v1
kind: Secret
metadata:
  name: git-private-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:c6h3un/argocd-demo-example.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
