apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  template:
    spec:
      containers:
        - name: httpd
          env: 
          - name: BG_COLOR
            value: LightBlue
          - name: APP_MESSAGE
            value: "echo app in ns2 namespace"
          - name: APP_NAME
            value: echo-ns2